// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvjeOntYEhgPcmRIYHxjxu9vSDJNvbpb0',
    appId: '1:935713876746:web:cfcfdde9931abbbb6ce8f3',
    messagingSenderId: '935713876746',
    projectId: 'greendealec',
    authDomain: 'greendealec.firebaseapp.com',
    storageBucket: 'greendealec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtehvpYSP7d5uFCb_-6I12ndQ7SooNNEk',
    appId: '1:935713876746:android:4c7f723ecb3fcfec6ce8f3',
    messagingSenderId: '935713876746',
    projectId: 'greendealec',
    storageBucket: 'greendealec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpO3y-q0eStljOBEZKbdg-n0OVxYJTToo',
    appId: '1:935713876746:ios:ef1f6205f763e8af6ce8f3',
    messagingSenderId: '935713876746',
    projectId: 'greendealec',
    storageBucket: 'greendealec.appspot.com',
    iosBundleId: 'com.example.ecomarket',
  );
}
